# Scraper APP config
selenide:
  timeout: 10000
  pageLoadTimeout: 90000

control-plane:
  url: "https://scraper-scraper-main.kube.agrp.dev/rest/v2/control"
  timeoutSeconds: 30
  apiKey: "your-api-key"

sources:
  whitelist: exa-scraper #here you can add source ID of source that you want to execute, also you can put here ALL, that will add all sources
  blacklist: #here you can add source ID of source that you don't want to execute, also you can also specify ALL here to ban all resources.
